package ui.form;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ui.UIController;
import ui.ViewModel;

import javax.swing.*;
import java.awt.*;
import java.util.Arrays;

public class LoginScreen {
    private JTextField userNameTextField;
    private JPasswordField passwordField;
    private JButton loginButton;
    private JPanel LoginPanel;
    private JButton helpButton;
    private JLabel passwordLabel;
    private JLabel usernameLabel;
    private JButton registerButton;
    private JButton testButton;

    private final UIController controller;

    public JPanel getLoginPanel() {
        return LoginPanel;
    }


    public LoginScreen() {
        controller = ViewModel.getInstance().getController();

        /*
         * Handle transitions to BuildScreen
         *
         * This also clears passwordField for security
         */
        loginButton.addActionListener(e -> {
                    var password = passwordField.getPassword();
                    passwordField.setText(null);
                    controller.loginValidate(userNameTextField.getText(), password);
                    Arrays.fill(password, '0');
                }
        );
        /*
         * Handle transitions to HelpScreen
         */
        helpButton.addActionListener(e -> controller.ShowHelpScreen());
        /*
         * Handle transitions to RegisterScreen
         */
        registerButton.addActionListener(e -> controller.ShowRegisterScreen());
        /*
         * Bypass Login
         */
        testButton.addActionListener(e -> controller.ShowBuildScreen());
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("LoginScreen");
        frame.setContentPane(new LoginScreen().LoginPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        LoginPanel = new JPanel();
        LoginPanel.setLayout(new GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
        LoginPanel.setAlignmentX(0.5f);
        LoginPanel.setFocusCycleRoot(false);
        LoginPanel.setMinimumSize(new Dimension(500, 300));
        usernameLabel = new JLabel();
        usernameLabel.setText("Username");
        LoginPanel.add(usernameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(76, 65), null, 0, false));
        userNameTextField = new JTextField();
        LoginPanel.add(userNameTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        passwordLabel = new JLabel();
        passwordLabel.setText("Password");
        LoginPanel.add(passwordLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(76, 54), null, 0, false));
        passwordField = new JPasswordField();
        LoginPanel.add(passwordField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        loginButton = new JButton();
        loginButton.setBorderPainted(false);
        loginButton.setContentAreaFilled(false);
        loginButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/loginIcon.png")));
        loginButton.setLabel("");
        loginButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/loginSelected.png")));
        loginButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/loginSelected.png")));
        loginButton.setText("");
        LoginPanel.add(loginButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        registerButton = new JButton();
        registerButton.setBorderPainted(false);
        registerButton.setContentAreaFilled(false);
        registerButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/registerIcon.png")));
        registerButton.setLabel("");
        registerButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/registerSelected.png")));
        registerButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/registerSelected.png")));
        registerButton.setText("");
        LoginPanel.add(registerButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        helpButton = new JButton();
        helpButton.setBorderPainted(false);
        helpButton.setContentAreaFilled(false);
        helpButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/helpIcon.png")));
        helpButton.setLabel("");
        helpButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/helpIconSelected.png")));
        helpButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/helpIconSelected.png")));
        helpButton.setText("");
        LoginPanel.add(helpButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        testButton = new JButton();
        testButton.setBorderPainted(false);
        testButton.setContentAreaFilled(false);
        testButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/testIcon.png")));
        testButton.setLabel("");
        testButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/testSelected.png")));
        testButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/testSelected.png")));
        testButton.setText("");
        LoginPanel.add(testButton, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return LoginPanel;
    }

}
