package ui.form;

import ui.ViewModel;

import javax.swing.*;

/**
 * MainForm is the Entry Point class that instantiates all other UI forms and adds them to the JPanel object owned by
 * the view model, and then puts them into the frame it creates.
 *
 * @implNote It might be sound to move this class to somewhere it is more visible
 */
public class MainForm {
    private JPanel cards;

    private void createUIComponents() {
        cards = ViewModel.getInstance().getPanels();
        cards.add(new LoginScreen().getLoginPanel(), "LOGIN");
        cards.add(new RegisterScreen().getRegisterPanel(), "REGISTER");
        cards.add(new HelpScreen().getHelpPanel(), "HELP");
        cards.add(new BuildScreen().getBuildPanel(), "BUILD");
        cards.add(new GameScreen().getGamePanel(), "GAME");
        cards.add(new PauseScreen().getPausePanel(), "PAUSE");
        cards.add(new VictoryScreen().getVictoryPanel(), "VICTORY");

    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("MainForm");
        frame.setContentPane(new MainForm().cards);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        cards.setDoubleBuffered(false);
        cards.setFocusTraversalPolicyProvider(false);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return cards;
    }
}
