package ui.form;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ui.ViewModel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class PauseScreen {
    private JButton resumeGameButton;
    private JPanel pausePanel;
    private JButton helpButton;
    private JButton returnToBuildModeButton;
    private JButton logOutButton;
    private JButton exitButton;
    private JButton saveAndExitButton;
    private JButton quickSaveButton;
    private JButton quickLoadButton;

    public JPanel getPausePanel() {
        return this.pausePanel;
    }

    public PauseScreen() {
        var controller = ViewModel.getInstance().getController();
        resumeGameButton.addActionListener(e -> controller.ShowGameScreenForced());
        helpButton.addActionListener(e -> controller.ShowHelpScreen());
        returnToBuildModeButton.addActionListener(e -> {
            controller.newGame();
            controller.ShowBuildScreen();
        });
        logOutButton.addActionListener(e -> controller.ShowLoginScreen());
        exitButton.addActionListener(e -> {
            // The lazy approach
            System.exit(0);
        });
        quickSaveButton.addActionListener(e -> {
            controller.saveGame();
            controller.ShowGameScreenForced();
        });
        quickLoadButton.addActionListener(e -> {
            controller.loadGame();
            controller.ShowGameScreenForced();
        });
        saveAndExitButton.addActionListener(e -> {
            controller.saveGame();
            System.exit(0);
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pausePanel = new JPanel();
        pausePanel.setLayout(new GridLayoutManager(8, 1, new Insets(0, 0, 0, 0), -1, -1));
        resumeGameButton = new JButton();
        resumeGameButton.setBorderPainted(false);
        resumeGameButton.setContentAreaFilled(false);
        resumeGameButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/resumeIcon.png")));
        resumeGameButton.setLabel("");
        resumeGameButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/resumeSelected.png")));
        resumeGameButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/resumeSelected.png")));
        resumeGameButton.setText("");
        pausePanel.add(resumeGameButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        helpButton = new JButton();
        helpButton.setBorderPainted(false);
        helpButton.setContentAreaFilled(false);
        helpButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/helpIcon.png")));
        helpButton.setLabel("");
        helpButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/helpIconSelected.png")));
        helpButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/helpIconSelected.png")));
        helpButton.setText("");
        pausePanel.add(helpButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        returnToBuildModeButton = new JButton();
        returnToBuildModeButton.setBorderPainted(false);
        returnToBuildModeButton.setContentAreaFilled(false);
        returnToBuildModeButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/buildmodeIcon.png")));
        returnToBuildModeButton.setLabel("");
        returnToBuildModeButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/buildmodeSelected.png")));
        returnToBuildModeButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/buildmodeSelected.png")));
        returnToBuildModeButton.setText("");
        pausePanel.add(returnToBuildModeButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logOutButton = new JButton();
        logOutButton.setBorderPainted(false);
        logOutButton.setContentAreaFilled(false);
        logOutButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/logoutIcon.png")));
        logOutButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/logoutSelected.png")));
        logOutButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/logoutSelected.png")));
        logOutButton.setText("");
        pausePanel.add(logOutButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        exitButton = new JButton();
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/exitwsavingIcon.png")));
        exitButton.setLabel("");
        exitButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/exitwsavingSelected.png")));
        exitButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/exitwsavingSelected.png")));
        exitButton.setText("");
        pausePanel.add(exitButton, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        saveAndExitButton = new JButton();
        saveAndExitButton.setBorderPainted(false);
        saveAndExitButton.setContentAreaFilled(false);
        saveAndExitButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/saveandexitIcon.png")));
        saveAndExitButton.setLabel("");
        saveAndExitButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/saveandexitSelected.png")));
        saveAndExitButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/saveandexitSelected.png")));
        saveAndExitButton.setText("");
        pausePanel.add(saveAndExitButton, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        quickSaveButton = new JButton();
        quickSaveButton.setBorderPainted(false);
        quickSaveButton.setContentAreaFilled(false);
        quickSaveButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/quicksaveIcon.png")));
        quickSaveButton.setLabel("");
        quickSaveButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/quicksaveSelected.png")));
        quickSaveButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/quicksaveSelected.png")));
        quickSaveButton.setText("");
        pausePanel.add(quickSaveButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        quickLoadButton = new JButton();
        quickLoadButton.setBorderPainted(false);
        quickLoadButton.setContentAreaFilled(false);
        quickLoadButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/quickloadIcon.png")));
        quickLoadButton.setLabel("");
        quickLoadButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/quickloadSelected.png")));
        quickLoadButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/quickloadSelected.png")));
        quickLoadButton.setText("");
        pausePanel.add(quickLoadButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pausePanel;
    }

}
