package ui.form;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ui.UIController;
import ui.ViewModel;

import javax.swing.*;
import java.awt.*;
import java.util.Arrays;

public class RegisterScreen {
    private JButton backButton;
    private JPanel RegisterPanel;
    private JTextField usernameField;
    private JPasswordField passwordField;
    private JButton submitButton;
    private JLabel usernameLabel;
    private JLabel passwordLabel;
    private JButton helpButton;
    private final UIController controller;

    public static void main(String[] args) {
        JFrame frame = new JFrame("RegisterScreen");
        frame.setContentPane(new RegisterScreen().RegisterPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public RegisterScreen() {
        controller = ViewModel.getInstance().getController();


        backButton.addActionListener(e -> controller.ShowPreviousScreen());

        submitButton.addActionListener(e -> {
            // Get the username and password from the JTextField and JPasswordField
            String username = usernameField.getText();
            char[] password = passwordField.getPassword();

            controller.registerAccount(username, password);
            Arrays.fill(password, '\0');

            // Clear the username and password fields for the next registration
            usernameField.setText("");
            passwordField.setText("");
        });

        helpButton.addActionListener(e -> controller.ShowHelpScreen());
    }

    public JPanel getRegisterPanel() {
        return RegisterPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        RegisterPanel = new JPanel();
        RegisterPanel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        usernameField = new JTextField();
        RegisterPanel.add(usernameField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        usernameLabel = new JLabel();
        usernameLabel.setText("Username");
        RegisterPanel.add(usernameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordLabel = new JLabel();
        passwordLabel.setText("Password");
        RegisterPanel.add(passwordLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordField = new JPasswordField();
        RegisterPanel.add(passwordField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        helpButton = new JButton();
        helpButton.setBorderPainted(false);
        helpButton.setContentAreaFilled(false);
        helpButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/helpIcon.png")));
        helpButton.setLabel("");
        helpButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/helpIconSelected.png")));
        helpButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/helpIconSelected.png")));
        helpButton.setText("");
        RegisterPanel.add(helpButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        backButton = new JButton();
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/backIcon.png")));
        backButton.setLabel("");
        backButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/backSelected.png")));
        backButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/backSelected.png")));
        backButton.setText("");
        RegisterPanel.add(backButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        submitButton = new JButton();
        submitButton.setBorderPainted(false);
        submitButton.setContentAreaFilled(false);
        submitButton.setIcon(new ImageIcon(getClass().getResource("/button-icons/submitIcon.png")));
        submitButton.setLabel("");
        submitButton.setRolloverIcon(new ImageIcon(getClass().getResource("/button-icons/submitSelected.png")));
        submitButton.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/button-icons/submitSelected.png")));
        submitButton.setText("");
        RegisterPanel.add(submitButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return RegisterPanel;
    }

}
